import java.util.List;
import java.lang.Boolean;
import java.lang.IllegalArgumentException;
import java.lang.Exception;
import java.lang.NullPointerException;
import java.lang.Object;

function main(List argv) {
	testTryCatch();
	testFinally();
}
function testTryCatch() {
	// catch an exception out of several possible, try same catch with different exceptions
	var r = try illegalArgThrower() catch IllegalArgumentException e: true catch Exception e: false endtry;
	assertTrue("should have caught IllegalArgumentException", r);
	r = try illegalArgThrower() catch Exception e: false  catch IllegalArgumentException e: true endtry;
	assertFalse("should have caught Exception", r);
	r = try illegalArgThrower() catch NullPointerException e: false  catch IllegalArgumentException e: true endtry;
	assertTrue("should have caught IllegalArgumentException", r);
}
function testFinally() {
	// test that finally is evaluated no matter what
	Boolean flag = false; 
	var r = try illegalArgThrower() catch IllegalArgumentException e: true finally flag = true endtry;
	assertTrue("finally should have been triggered", flag);
	flag = false;
	r = try true catch IllegalArgumentException e: true finally flag = true endtry;
	assertTrue("finally should have been triggered", flag);
}

/**
* Always throws java.lang.IllegalArgumentException.
*/
function Boolean illegalArgThrower() {
	throw new IllegalArgumentException();
	// unreachable...
}